[workspace]
members = [
  "kernel",
  "application",
  "driver",
  "server"
]
resolver = "2"


[workspace.dependencies]
anyhow = "1"
thiserror = "1"

# feat(lib)!: transfer from `thiserror` and `anyhow`
error-stack = "0.5.0"