name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: ShuttlePub/workflows/.github/workflows/check.yml@main
    with:
      gen_coverage: true
    secrets: inherit
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
