name: Validate PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    
jobs:
  validate:
    uses: ShuttlePub/workflows/.github/workflows/validate-pr.yml@main
  
